In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [1]:
from google.colab import files
uploaded = files.upload()

Saving iris (1).csv to iris (1).csv


In [6]:
iris = pd.read_csv("/content/iris (1).csv")
iris.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [7]:
X = iris.iloc[:, :-1]   # Features
y = iris.iloc[:, -1]    # Target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [8]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [9]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [11]:
from google.colab import files
uploaded = files.upload()

Saving petrol_consumption.csv to petrol_consumption.csv


In [12]:
petrol = pd.read_csv("/content/petrol_consumption.csv")
petrol.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410


In [13]:
X = petrol.iloc[:, :-1]   # Features
y = petrol.iloc[:, -1]    # Target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [14]:
reg_model = DecisionTreeRegressor()
reg_model.fit(X_train, y_train)

DecisionTreeRegressor()

In [15]:
y_pred = reg_model.predict(X_test)

In [16]:
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

MAE: 88.2
MSE: 15699.8
RMSE: 125.29884277199051


In [17]:
for name, importance in zip(X.columns, reg_model.feature_importances_):
    print(name, ":", importance)

Petrol_tax : 0.0679803119829229
Average_income : 0.22672746449435363
Paved_Highways : 0.04506926688285025
Population_Driver_licence(%) : 0.6602229566398732
